[package]
name = "rascaline"
version = "0.1.0"
authors = ["Luthaf <luthaf@luthaf.fr>"]
edition = "2021"
rust-version = "1.61"

[lib]
bench = false

[features]
# We use a static version of equistore by default since otherwise doctests can
# not find libequistore.so
default = ["chemfiles", "static-equistore"]

static-equistore = ["equistore/static"]

[[bench]]
name = "spherical-harmonics"
harness = false

[[bench]]
name = "soap-radial-integral"
harness = false

[[bench]]
name = "lode-spherical-expansion"
harness = false

[[bench]]
name = "soap-spherical-expansion"
harness = false

[[bench]]
name = "soap-power-spectrum"
harness = false

[dependencies]
equistore = {git = "https://github.com/m-stack-org/equistore", rev = "b8a65fa", features = ["rayon"]}

ndarray = {version = "0.15", features = ["approx-0_5", "rayon", "serde"]}
num-traits = "0.2"
rayon = "1.5"

log = "0.4"
once_cell = "1"
indexmap = "1.8"
thread_local = "1.1"
time-graph = "0.3.0"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"

chemfiles = {version = "0.10", optional = true}

approx = "0.5"

[dev-dependencies]
criterion = "0.4"
glob = "0.3"
ndarray-npy = "0.8"
flate2 = "1.0.20"
time-graph = {version = "0.3.0", features = ["table", "json"]}
